// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.9.178
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RestartVisualStudio
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string RestartVisualStudioPackageString = "8C473951-66AA-406C-B7D7-AA9F1C4FD55E";
        public const string RestartVisualStudioCommandSetString = "4eac4e23-4909-4dac-9d6e-819bdc861480";

        public static Guid RestartVisualStudioPackage = new Guid(RestartVisualStudioPackageString);
        public static Guid RestartVisualStudioCommandSet = new Guid(RestartVisualStudioCommandSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int RestartGroup = 0x0100;
        public const int RestartDropDown = 0x0101;
        public const int RestartCommands = 0x0102;

        public const int RestartNormalCommand = 0x0105;
        public const int RestartElevatedCommand = 0x0106;
    }
}
